api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "nuphy-free-gift-discount"
uid = "db2ce2f9-8f07-4e68-281e-7251e2212d3101060bd9"
type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "gobo-free-gift-discount-function"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
