# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4ccd118df9fc40c42d865fd151b0ec2a"
name = "nuphy-local-dev"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-01"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "61style.myshopify.com"
