# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0b479bbf5423a03aef633015db413c8d"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "nuphy-japan-extension-app"

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
