# Production configuration. Always select it explicitly with --config production.

client_id = "ea8902f04f9c9f1c5f6fd7ed25500b71"
name = "nuphy-extension-only-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-01"

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
